apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-t0kn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-t0kn
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-t0kn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-t0kn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-t0kn
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-flvf-tenant/status-quarkus-io/statusquarkusio-t0kn@sha256:2b269bfa1283c103af1c839f845cc50f0e34095eaa10f14dd9fb4e7df7d0b756
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
